import { createFileRoute } from "@tanstack/react-router";
import { useI18n } from "@/lib/i18n";
import { DataTable, KpiCard, PageHeader, Panel, Td } from "@/components/kit";
import { journal, kpis, trialBalance } from "@/lib/demo-data";

export const Route = createFileRoute("/accounting")({
  head: () => ({
    meta: [
      { title: "Accounting — Hafez ERP" },
      {
        name: "description",
        content: "Journal entries and trial balance, generated by business rules rather than by the AI itself.",
      },
      { property: "og:title", content: "Accounting — Hafez ERP" },
      { property: "og:description", content: "Journal entries and trial balance for the period." },
    ],
  }),
  component: Accounting,
});

function Accounting() {
  const { t, pick, money } = useI18n();
  const totalDebit = trialBalance.reduce((s, r) => s + r.debit, 0);
  const totalCredit = trialBalance.reduce((s, r) => s + r.credit, 0);

  return (
    <>
      <PageHeader
        title={t("nav_accounting")}
        subtitle={pick(
          "القيود تُنشأ من قواعد العمل، والذكاء الاصطناعي يشرح فقط",
          "Entries come from business rules; AI only explains them",
        )}
      />

      <div className="grid gap-4 sm:grid-cols-3">
        <KpiCard label={t("debit")} value={money(totalDebit)} accent="brand" />
        <KpiCard label={t("credit")} value={money(totalCredit)} accent="primary" />
        <KpiCard label={t("kpi_cash")} value={money(kpis.cash)} delta={kpis.cashDelta} accent="gold" />
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <Panel title={t("journal")}>
          <DataTable head={["#", t("date"), t("account"), t("debit"), t("credit")]}>
            {journal.map((j, idx) => (
              <tr key={`${j.id}-${idx}`} className="hover:bg-secondary">
                <Td className="num font-bold">{j.id}</Td>
                <Td className="num text-muted-foreground">{j.date}</Td>
                <Td>{pick(j.account.ar, j.account.en)}</Td>
                <Td className="num">{j.debit ? money(j.debit) : "—"}</Td>
                <Td className="num">{j.credit ? money(j.credit) : "—"}</Td>
              </tr>
            ))}
          </DataTable>
        </Panel>

        <Panel title={t("trialBalance")}>
          <DataTable head={[t("account"), t("debit"), t("credit")]}>
            {trialBalance.map((r) => (
              <tr key={r.account.en} className="hover:bg-secondary">
                <Td>{pick(r.account.ar, r.account.en)}</Td>
                <Td className="num">{r.debit ? money(r.debit) : "—"}</Td>
                <Td className="num">{r.credit ? money(r.credit) : "—"}</Td>
              </tr>
            ))}
            <tr>
              <Td className="font-bold uppercase">{pick("الإجمالي", "Total")}</Td>
              <Td className="num font-bold">{money(totalDebit)}</Td>
              <Td className="num font-bold">{money(totalCredit)}</Td>
            </tr>
          </DataTable>
        </Panel>
      </div>
    </>
  );
}
