import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { FolderTree, BookOpen, Scale } from "lucide-react";
import { useI18n } from "@/lib/i18n";
import { Btn, DataTable, KpiCard, PageHeader, Panel, Td } from "@/components/kit";
import { journal, kpis, trialBalance } from "@/lib/demo-data";
import { ChartOfAccounts } from "@/components/accounting/ChartOfAccounts";

export const Route = createFileRoute("/accounting")({
  head: () => ({
    meta: [
      { title: "Accounting & Chart of Accounts — Hafez ERP" },
      {
        name: "description",
        content: "Chart of accounts, journal entries, and trial balance generated by verified business rules.",
      },
      { property: "og:title", content: "Accounting — Hafez ERP" },
      { property: "og:description", content: "Chart of accounts, journal entries and trial balance." },
    ],
  }),
  component: Accounting,
});

function Accounting() {
  const { t, pick, money } = useI18n();
  const [activeTab, setActiveTab] = useState<"coa" | "journal" | "trial">("coa");

  const totalDebit = trialBalance.reduce((s, r) => s + r.debit, 0);
  const totalCredit = trialBalance.reduce((s, r) => s + r.credit, 0);

  return (
    <div className="space-y-6">
      <PageHeader
        title={t("nav_accounting")}
        subtitle={pick(
          "دليل الحسابات وقيود اليومية وميزان المراجعة — وفق القواعد المحاسبية المعتمدة",
          "Chart of accounts, journal entries and trial balance — according to standard accounting principles",
        )}
      />

      {/* Accounting View Tabs */}
      <div className="flex flex-wrap items-center gap-2 border-b border-border/70 pb-3">
        <Btn
          variant={activeTab === "coa" ? "solid" : "outline"}
          onClick={() => setActiveTab("coa")}
          className="text-xs"
        >
          <FolderTree className="size-4" />
          {t("chartOfAccounts")}
        </Btn>
        <Btn
          variant={activeTab === "journal" ? "solid" : "outline"}
          onClick={() => setActiveTab("journal")}
          className="text-xs"
        >
          <BookOpen className="size-4" />
          {t("journal")}
        </Btn>
        <Btn
          variant={activeTab === "trial" ? "solid" : "outline"}
          onClick={() => setActiveTab("trial")}
          className="text-xs"
        >
          <Scale className="size-4" />
          {t("trialBalance")}
        </Btn>
      </div>

      {/* Tab 1: Chart of Accounts */}
      {activeTab === "coa" && <ChartOfAccounts />}

      {/* Tab 2: Journal Entries */}
      {activeTab === "journal" && (
        <div className="space-y-6">
          <div className="grid gap-4 sm:grid-cols-3">
            <KpiCard label={t("debit")} value={money(totalDebit)} accent="brand" />
            <KpiCard label={t("credit")} value={money(totalCredit)} accent="primary" />
            <KpiCard label={t("kpi_cash")} value={money(kpis.cash)} delta={kpis.cashDelta} accent="gold" />
          </div>

          <Panel title={t("journal")}>
            <DataTable head={["#", t("date"), t("account"), t("debit"), t("credit")]}>
              {journal.map((j, idx) => (
                <tr key={`${j.id}-${idx}`} className="hover:bg-secondary">
                  <Td className="num font-bold">{j.id}</Td>
                  <Td className="num text-muted-foreground">{j.date}</Td>
                  <Td>{pick(j.account.ar, j.account.en)}</Td>
                  <Td className="num">{j.debit ? money(j.debit) : "—"}</Td>
                  <Td className="num">{j.credit ? money(j.credit) : "—"}</Td>
                </tr>
              ))}
            </DataTable>
          </Panel>
        </div>
      )}

      {/* Tab 3: Trial Balance */}
      {activeTab === "trial" && (
        <div className="space-y-6">
          <div className="grid gap-4 sm:grid-cols-3">
            <KpiCard label={t("debit")} value={money(totalDebit)} accent="brand" />
            <KpiCard label={t("credit")} value={money(totalCredit)} accent="primary" />
            <KpiCard label={t("kpi_cash")} value={money(kpis.cash)} delta={kpis.cashDelta} accent="gold" />
          </div>

          <Panel title={t("trialBalance")}>
            <DataTable head={[t("account"), t("debit"), t("credit")]}>
              {trialBalance.map((r) => (
                <tr key={r.account.en} className="hover:bg-secondary">
                  <Td>{pick(r.account.ar, r.account.en)}</Td>
                  <Td className="num">{r.debit ? money(r.debit) : "—"}</Td>
                  <Td className="num">{r.credit ? money(r.credit) : "—"}</Td>
                </tr>
              ))}
              <tr>
                <Td className="font-bold uppercase">{pick("الإجمالي", "Total")}</Td>
                <Td className="num font-bold">{money(totalDebit)}</Td>
                <Td className="num font-bold">{money(totalCredit)}</Td>
              </tr>
            </DataTable>
          </Panel>
        </div>
      )}
    </div>
  );
}
